import { View, Text, ScrollView, StyleSheet, ActivityIndicator, Image, Share, TouchableOpacity } from 'react-native';
import { useLocalSearchParams } from 'expo-router';
import { useState, useCallback } from 'react';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { useDatabase } from '../../../src/data/local/DatabaseProvider';
import { getJobById } from '../../../src/data/local/jobRepository';
import { getNotesByJobId } from '../../../src/data/local/noteRepository';
import { getMaterialsByJobId } from '../../../src/data/local/materialRepository';
import { getTimeEntriesByJobId } from '../../../src/data/local/timeEntryRepository';
import { getExtractionResultsByJobId } from '../../../src/data/local/extractionRepository';
import { getPhotosByJobId } from '../../../src/data/local/photoRepository';
import { formatDate } from '../../../src/utils/formatting';
import type { Job, JobNote, MaterialLineItem, TimeEntry, AiExtractionResult, PhotoAsset } from '../../../src/domain/types';
import { Colors, Spacing, Typography, BorderRadius, Elevation } from '../../../src/theme/colors';

function generateReportText(
  job: Job,
  notes: JobNote[],
  materials: MaterialLineItem[],
  timeEntries: TimeEntry[],
  extractedWorkPerformed: string[],
  extractedFollowUps: string[]
): string {
  const totalMinutes = timeEntries.reduce((sum, t) => sum + (t.durationMinutes ?? 0), 0);
  const totalCost = materials.reduce((sum, m) => sum + (m.totalCost ?? 0), 0);
  const lines: string[] = [];

  lines.push('=== JobTrail Report ===');
  lines.push('');
  lines.push(`Job: ${job.title}`);
  if (job.jobType) lines.push(`Type: ${job.jobType}`);
  lines.push(`Status: ${job.status.replace('_', ' ')}`);
  lines.push(`Date: ${new Date(job.createdAt).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('');

  if (extractedWorkPerformed.length > 0 || notes.length > 0) {
    lines.push('Work Performed:');
    extractedWorkPerformed.forEach(w => lines.push(`  • ${w}`));
    notes.forEach(n => lines.push(`  • ${n.content}`));
    lines.push('');
  }

  if (materials.length > 0) {
    lines.push('Materials Used:');
    materials.forEach(m => lines.push(`  • ${m.quantity} ${m.unit ?? ''} ${m.name}${m.totalCost ? ` — $${m.totalCost.toFixed(2)}` : ''}`));
    if (totalCost > 0) lines.push(`  Total: $${totalCost.toFixed(2)}`);
    lines.push('');
  }

  if (totalMinutes > 0) {
    lines.push(`Labor Time: ${totalMinutes} minutes (${Math.floor(totalMinutes / 60)}h ${totalMinutes % 60}m)`);
    timeEntries.forEach(t => lines.push(`  • ${t.durationMinutes} min${t.description ? ` — ${t.description}` : ''}`));
    lines.push('');
  }

  if (extractedFollowUps.length > 0) {
    lines.push('Follow-up:');
    extractedFollowUps.forEach(f => lines.push(`  • ${f}`));
    lines.push('');
  }

  if (job.internalNotes) {
    lines.push('Notes:');
    lines.push(`  ${job.internalNotes}`);
    lines.push('');
  }

  lines.push('---');
  lines.push(`Generated by JobTrail — ${new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}`);

  return lines.join('\n');
}

export default function ReportPreviewScreen() {
  const { id } = useLocalSearchParams<{ id: string }>();
  const db = useDatabase();

  const [job, setJob] = useState<Job | null>(null);
  const [notes, setNotes] = useState<JobNote[]>([]);
  const [photos, setPhotos] = useState<PhotoAsset[]>([]);
  const [materials, setMaterials] = useState<MaterialLineItem[]>([]);
  const [timeEntries, setTimeEntries] = useState<TimeEntry[]>([]);
  const [extractions, setExtractions] = useState<AiExtractionResult[]>([]);
  const [loading, setLoading] = useState(true);

  const loadData = useCallback(async () => {
    if (!id) return;
    try {
      const [j, n, p, m, t, e] = await Promise.all([
        getJobById(db, id),
        getNotesByJobId(db, id),
        getPhotosByJobId(db, id),
        getMaterialsByJobId(db, id),
        getTimeEntriesByJobId(db, id),
        getExtractionResultsByJobId(db, id),
      ]);
      setJob(j);
      setNotes(n);
      setPhotos(p);
      setMaterials(m);
      setTimeEntries(t);
      setExtractions(e);
    } catch (error) {
      console.error('Failed to load report data:', error);
    } finally {
      setLoading(false);
    }
  }, [db, id]);

  useFocusEffect(
    useCallback(() => {
      loadData();
    }, [loadData])
  );

  if (loading) {
    return <View style={styles.centerContainer}><ActivityIndicator size="large" color={Colors.primary} /></View>;
  }

  if (!job) {
    return <View style={styles.centerContainer}><Text style={styles.emptyText}>Job not found</Text></View>;
  }

  const totalMinutes = timeEntries.reduce((sum, t) => sum + (t.durationMinutes ?? 0), 0);
  const totalCost = materials.reduce((sum, m) => sum + (m.totalCost ?? 0), 0);

  // Get accepted extraction data
  const acceptedExtractions = extractions.filter((e) => e.acceptedAt);
  let extractedFollowUps: string[] = [];
  let extractedWorkPerformed: string[] = [];

  for (const ext of acceptedExtractions) {
    try {
      const parsed = JSON.parse(ext.extractedJson);
      if (parsed.followUpNotes) extractedFollowUps = [...extractedFollowUps, ...parsed.followUpNotes];
      if (parsed.workPerformed) extractedWorkPerformed = [...extractedWorkPerformed, ...parsed.workPerformed];
    } catch { /* skip malformed */ }
  }

  const handleShare = async () => {
    const text = generateReportText(job, notes, materials, timeEntries, extractedWorkPerformed, extractedFollowUps);
    try {
      await Share.share({ message: text, title: `JobTrail Report: ${job.title}` });
    } catch (error) {
      console.error('Share failed:', error);
    }
  };

  return (
    <ScrollView style={styles.container} contentContainerStyle={styles.scrollContent}>
      {/* Header */}
      <View style={styles.reportHeader}>
        <View style={styles.reportTitleRow}>
          <Ionicons name="document-text-outline" size={24} color={Colors.primary} />
          <Text style={styles.reportTitle}>JobTrail Report</Text>
        </View>
        <Text style={styles.reportSubtitle}>{job.title}</Text>
        {job.jobType && <Text style={styles.reportMeta}>Type: {job.jobType}</Text>}
        <Text style={styles.reportMeta}>Status: {job.status.replace('_', ' ')}</Text>
        <Text style={styles.reportMeta}>Date: {formatDate(job.createdAt, 'long')}</Text>
      </View>

      {/* Customer Summary */}
      {job.customerVisibleSummary && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="person-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Customer Summary</Text>
          </View>
          <Text style={styles.customerSummary}>{job.customerVisibleSummary}</Text>
        </View>
      )}

      <View style={styles.divider} />

      {/* Work Performed */}
      {(extractedWorkPerformed.length > 0 || notes.length > 0) && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="construct-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Work Performed</Text>
          </View>
          {extractedWorkPerformed.map((w, i) => (
            <Text key={i} style={styles.bulletItem}>• {w}</Text>
          ))}
          {notes.map((n) => (
            <Text key={n.id} style={styles.bulletItem}>• {n.content}</Text>
          ))}
        </View>
      )}

      {/* Photos */}
      {photos.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="camera-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Photos</Text>
          </View>
          <View style={styles.photoGrid}>
            {photos.map((photo) => (
              <View key={photo.id} style={styles.photoItem}>
                <Image source={{ uri: photo.localUri }} style={styles.photoImage} />
                <Text style={styles.photoTypeLabel}>{photo.photoType}</Text>
                {photo.caption && <Text style={styles.photoCaption}>{photo.caption}</Text>}
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Materials */}
      {materials.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="cube-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Materials Used</Text>
          </View>
          {materials.map((m) => (
            <View key={m.id} style={styles.materialRow}>
              <Text style={styles.bulletItem}>{m.quantity} {m.unit ?? ''} {m.name}</Text>
              {m.totalCost !== null && m.totalCost > 0 && (
                <Text style={styles.costText}>${m.totalCost.toFixed(2)}</Text>
              )}
            </View>
          ))}
          {totalCost > 0 && (
            <Text style={styles.totalCost}>Total: ${totalCost.toFixed(2)}</Text>
          )}
        </View>
      )}

      {/* Labor Time */}
      {totalMinutes > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="time-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Labor Time</Text>
          </View>
          <Text style={styles.bulletItem}>
            Total: {totalMinutes} minutes ({Math.floor(totalMinutes / 60)}h {totalMinutes % 60}m)
          </Text>
          {timeEntries.map((t) => (
            <Text key={t.id} style={styles.subBulletItem}>
              • {t.durationMinutes} min{t.description ? ` — ${t.description}` : ''}
            </Text>
          ))}
        </View>
      )}

      {/* Follow-up Notes */}
      {extractedFollowUps.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="alert-circle-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Follow-up</Text>
          </View>
          {extractedFollowUps.map((f, i) => (
            <Text key={i} style={styles.bulletItem}>• {f}</Text>
          ))}
        </View>
      )}

      {/* Internal Notes */}
      {job.internalNotes && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="document-text-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Notes</Text>
          </View>
          <Text style={styles.bulletItem}>{job.internalNotes}</Text>
        </View>
      )}

      {/* Rough Notes */}
      {job.roughNotes && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Ionicons name="create-outline" size={18} color={Colors.primary} />
            <Text style={styles.sectionTitle}>Original Notes</Text>
          </View>
          <Text style={styles.roughNotes}>{job.roughNotes}</Text>
        </View>
      )}

      {/* Share Report */}
      <TouchableOpacity style={styles.shareButton} onPress={handleShare}>
        <Ionicons name="share-outline" size={20} color={Colors.text} />
        <Text style={styles.shareButtonText}>Share Report</Text>
      </TouchableOpacity>

      {/* Footer */}
      <View style={styles.reportFooter}>
        <Text style={styles.footerText}>Generated by JobTrail</Text>
        <Text style={styles.footerText}>{formatDate(new Date().toISOString(), 'long')}</Text>
      </View>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.background },
  scrollContent: { padding: Spacing.lg, paddingBottom: 40 },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: Colors.background },
  emptyText: { fontSize: Typography.fontSize.lg, color: Colors.textSecondary },
  reportHeader: { marginBottom: Spacing.lg, backgroundColor: Colors.surface, borderRadius: BorderRadius.md, padding: Spacing.lg, ...Elevation.low },
  reportTitleRow: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.xs },
  reportTitle: { fontSize: Typography.fontSize.xxl, fontWeight: Typography.fontWeight.bold as any, color: Colors.primary },
  reportSubtitle: { fontSize: Typography.fontSize.xl, fontWeight: Typography.fontWeight.semibold as any, color: Colors.text, marginBottom: Spacing.sm },
  reportMeta: { fontSize: Typography.fontSize.sm, color: Colors.textSecondary, marginBottom: 2 },
  divider: { height: 1, backgroundColor: Colors.border, marginBottom: Spacing.lg, opacity: 0.5 },
  section: { marginBottom: Spacing.xl },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', gap: Spacing.sm, marginBottom: Spacing.sm, borderBottomWidth: 1, borderBottomColor: Colors.border, paddingBottom: Spacing.xs },
  sectionTitle: { fontSize: Typography.fontSize.lg, fontWeight: Typography.fontWeight.semibold as any, color: Colors.text },
  bulletItem: { fontSize: Typography.fontSize.md, color: Colors.text, lineHeight: 24, marginBottom: 2 },
  subBulletItem: { fontSize: Typography.fontSize.sm, color: Colors.textSecondary, lineHeight: 20, marginLeft: Spacing.md },
  materialRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 2 },
  costText: { fontSize: Typography.fontSize.md, color: Colors.textSecondary },
  totalCost: { fontSize: Typography.fontSize.md, fontWeight: Typography.fontWeight.semibold as any, color: Colors.text, marginTop: Spacing.sm },
  roughNotes: { fontSize: Typography.fontSize.sm, color: Colors.textTertiary, fontStyle: 'italic' as any, lineHeight: 20 },
  reportFooter: { marginTop: Spacing.xxl, paddingTop: Spacing.lg, borderTopWidth: 1, borderTopColor: Colors.border, alignItems: 'center' },
  footerText: { fontSize: Typography.fontSize.xs, color: Colors.textTertiary },
  photoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: Spacing.sm },
  photoItem: { width: '48%', marginBottom: Spacing.sm },
  photoImage: { width: '100%', height: 120, borderRadius: BorderRadius.md, backgroundColor: Colors.surfaceSecondary },
  photoTypeLabel: { fontSize: Typography.fontSize.xs, color: Colors.primary, fontWeight: '500' as any, marginTop: 2, textTransform: 'uppercase' as any },
  photoCaption: { fontSize: Typography.fontSize.xs, color: Colors.textSecondary, marginTop: 1 },
  customerSummary: { fontSize: Typography.fontSize.md, color: Colors.text, lineHeight: 24, backgroundColor: Colors.surfaceSecondary, borderRadius: BorderRadius.md, padding: Spacing.md, fontStyle: 'italic' as any },
  shareButton: { backgroundColor: Colors.surfaceSecondary, borderRadius: BorderRadius.md, padding: Spacing.lg, flexDirection: 'row', gap: Spacing.sm, justifyContent: 'center', alignItems: 'center', marginTop: Spacing.md, borderWidth: 1, borderColor: Colors.border, ...Elevation.medium },
  shareButtonText: { color: Colors.text, fontSize: Typography.fontSize.lg, fontWeight: Typography.fontWeight.semibold as any },
});