"""Coverage report for eval drafts (#70): what was planned, what was drafted, and how
many drafts came back without a single fidelity flag ("clean")."""

from __future__ import annotations

from collections import Counter
from typing import Any

from .sampler import TAGS

PLAIN = "(plain)"


def _keys(tags: list[str]) -> list[str]:
    return tags or [PLAIN]


def coverage_table(plans: list[dict], drafts: list[dict]) -> dict[str, dict[str, int]]:
    table = {t: dict.fromkeys(
        ["test_planned", "test_drafted", "test_clean", "dev_planned", "dev_drafted"], 0)
        for t in [*TAGS, PLAIN]}  # fmt: skip
    for p in plans:
        for k in _keys(p["tags"]):
            table[k][f"{p['split']}_planned"] += 1
    for d in drafts:
        split = d["meta"]["split"]
        for k in _keys(d["tags"]):
            table[k][f"{split}_drafted"] += 1
            if split == "test" and not d["meta"]["flags"]:
                table[k]["test_clean"] += 1
    return table


def coverage_markdown(
    plans: list[dict], drafts: list[dict], usage: dict[str, Any], min_test: int
) -> str:
    table = coverage_table(plans, drafts)
    n = Counter(d["meta"]["split"] for d in drafts)
    planned = Counter(p["split"] for p in plans)
    flagged = sum(1 for d in drafts if d["meta"]["flags"])
    lines = [
        "# Eval draft coverage",
        "",
        "Generated by `uv run python scripts/gen_eval_notes.py report`. Drafts are **not gold**"
        " until verified in the labeling tool (#71).",
        "",
        f"Drafted: test {n['test']}/{planned['test']}, dev {n['dev']}/{planned['dev']}. "
        f"Drafts with at least one fidelity flag: {flagged}/{len(drafts)}.",
        "",
        "| Tag | Test planned | Test drafted | Test clean | Dev planned | Dev drafted |",
        "| --- | ---: | ---: | ---: | ---: | ---: |",
    ]
    short = []
    for tag, row in table.items():
        lines.append(
            f"| {tag} | {row['test_planned']} | {row['test_drafted']} | {row['test_clean']} "
            f"| {row['dev_planned']} | {row['dev_drafted']} |"
        )
        if tag != PLAIN and row["test_drafted"] < min_test:
            short.append(tag)
    lines += [
        "",
        f"Target: every tag has ≥ {min_test} test drafts, so ≥ 8 survive review. "
        + (f"**Below {min_test}:** {', '.join(short)}." if short else "All tags meet it."),
        "",
        "## Fidelity flags",
        "",
        "Pointers for the reviewer, not verdicts. `crosscheck:*` = a different model's blind "
        "extraction disagrees with the plan.",
        "",
        "| Flag | Drafts |",
        "| --- | ---: |",
    ]
    kinds = Counter(f.split(":")[0] if not f.startswith("crosscheck") else ":".join(
        f.split(":")[:2]) for d in drafts for f in d["meta"]["flags"])  # fmt: skip
    lines += [f"| {k} | {v} |" for k, v in kinds.most_common()] or ["| (none) | 0 |"]
    lines += [
        "",
        "## Usage",
        "",
        f"{usage.get('calls', 0):,} API calls, {usage.get('total', 0):,} tokens in total "
        "(per-call counts in `usage.jsonl`; billing tier and cost are recorded in data/README).",
        "",
    ]
    return "\n".join(lines)
